POST http://localhost:8080/v1/api/students/sttopic
Content-Type: application/json

{
  "name": "CarTopic2",
  "lastName": "CarTopic2",
  "email": "topic@gmail.com"
}

###
POST http://localhost:8080/v1/api/students/stfanaout
Content-Type: application/json

{
  "name": "CarFan",
  "lastName": "CarFan",
  "email": "car@gmail.com"
}

###
POST http://localhost:8080/v1/api/students/stdirec
Content-Type: application/json

{
  "name": "Car",
  "lastName": "Car",
  "email": "car@gmail.com"
}

###
POST http://localhost:8080/v1/api/producer
Content-Type: application/json

{
  "message": "Enviando mensaje2"
}
###
